services:
  one-service:
    restart: on-failure
    privileged: true

  two-service:
    restart: no

  three-service:
    restart: unless-stopped
    volumes:
      - /test/paths:/test/paths:ro
      - /example/path:/mnt/example/path
    privileged: false

  four-service:
    volumes:
      - /test/path:/test/path
    restart: 'no'
