services:
  one-service:
    restart: on-failure

  two-service:
    restart: no

  three-service:
    restart: unless-stopped
    volumes:
      - /test/paths:/test/paths:ro

  four-service:
    volumes:
      - /test/path:/test/path
